### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by dbock1989** [SejoslawMods/CatchEverythingInBook#3]
Minecraft: 1.14.4
Server: BoxyWorld Modpack
Version of mod:1.0.0
Forge Version: 28.1.90

[17Nov2019 11:27:47.208] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;
	Index: 17
	Listeners:
		0: HIGHEST
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2407/1509101341@3e043bb
		2: ASM: net.quetzi.morpheus.helpers.MorpheusEventHandler@27693971 bedClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		3: ASM: mokiyoki.enhancedanimals.util.handlers.EventSubscriber@5201fbe5 onBlockInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		4: HIGH
		5: ASM: com.blakebr0.pickletweaks.tweaks.TweakToolBreaking@11e1c73d onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		6: ASM: tschipp.carryon.common.event.ItemEntityEvents@30eaf203 onBlockClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		7: NORMAL
		8: ASM: class net.geforcemods.securitycraft.SCEventHandler onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		9: net.minecraftforge.eventbus.EventBus$$Lambda$2407/1509101341@7e270d15
		10: ASM: class tschipp.carryon.common.event.ItemEvents onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		11: ASM: class net.silentchaos512.gear.event.ToolBlockPlaceHandler onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		12: ASM: class com.tfar.dankstorage.event.DankEventHandler wrench(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		13: ASM: class com.tfar.cursedearth.CursedEarth$Rose applyRose(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		14: net.minecraftforge.eventbus.EventBus$$Lambda$2407/1509101341@24e94fde
		15: net.minecraftforge.eventbus.EventBus$$Lambda$2407/1509101341@63a9f14d
		16: ASM: class net.telepathicgrunt.ultraamplified.blockbehavior.AmplifiedPortalBehavior$ForgeEvents BlockRightClickEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		17: ASM: com.github.sejoslaw.catchEverythingInBook.CatchBlockHandler@66a3f41b onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		18: ASM: com.github.sejoslaw.catchEverythingInBook.CatchEntityHandler@33c3a934 releaseEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		19: ASM: class com.simibubi.create.Events onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		20: ASM: svenhjol.charm.brewing.feature.FlavoredCake@240159f onPotionUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		21: ASM: svenhjol.charm.world.feature.CompassBinding@634d53a0 onCompassUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		22: ASM: svenhjol.charm.tweaks.feature.RecordsStopBackgroundMusic@1485d27e onBlockInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		23: ASM: class phrille.minecraftboom.handler.PlayerEventHandler onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		24: ASM: class me.KG20.supertools.Event.EventHandler SuperShovelRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		25: ASM: class me.KG20.supertools.Event.EventHandler SuperHoeRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		26: net.minecraftforge.eventbus.EventBus$$Lambda$2407/1509101341@62558b18
		27: ASM: class com.stal111.forbidden_arcanus.event.BlockActivatedListener onItemRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		28: net.minecraftforge.eventbus.EventBus$$Lambda$2407/1509101341@245c7de2
		29: ASM: io.github.strikerrocker.vt.tweaks.SignEditing@c4b7d61 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		30: ASM: io.github.strikerrocker.vt.tweaks.sit.Sit@5e90f417 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		31: ASM: com.blakebr0.pickletweaks.feature.FeatureRightClickHarvest@120d384f onRightClickCrop(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		32: ASM: enemeez.simplefarming.events.DoubleCropBreak@b8bc987 onCropRightClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		33: ASM: enemeez.simplefarming.events.harvest.BerryBushHarvest@345d2fbf onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		34: ASM: enemeez.simplefarming.events.harvest.CactusCropHarvest@3bf92301 onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		35: ASM: enemeez.simplefarming.events.harvest.CropHarvest@50bbd4c2 onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		36: ASM: enemeez.simplefarming.events.harvest.DoubleCropHarvest@34a4b44f onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		37: ASM: enemeez.simplefarming.events.harvest.FruitLeavesHarvest@5e000ef6 onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		38: ASM: enemeez.simplefarming.events.harvest.GrapeHarvest@69555535 onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		39: ASM: enemeez.simplefarming.events.harvest.WildPlantHarvest@4decefbf onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		40: ASM: shadows.apotheosis.ench.EnchModule@a1758e1 rightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		41: ASM: tschipp.carryon.common.capabilities.event.PositionCommonEvents@415a3c6f onBlockRight(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		42: ASM: com.legacy.rediscovered.event.RediscoveredEvents@2b5dabe0 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		43: ASM: com.natamus.endportalrecipe.events.EndPortalEvent@407a7642 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		44: ASM: vazkii.quark.tweaks.module.DirtToPathModule@25c4b936 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		45: ASM: vazkii.quark.tweaks.module.EnchancedLaddersModule@383e2930 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		46: ASM: vazkii.quark.tweaks.module.SignEditingModule@531a032b onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		47: ASM: vazkii.quark.tweaks.module.SimpleHarvestModule@6b25ac25 onClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		48: ASM: class com.stal111.forbidden_arcanus.event.PlayerInteractListener onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		49: ASM: mcjty.rftoolsutility.setup.ForgeEventHandlers@607f299 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		50: LOWEST
		51: ASM: class ovh.corail.tombstone.event.EventHandler onRightClickChest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		52: ASM: class ovh.corail.tombstone.event.EventHandler uncancelGraveRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
java.lang.NoSuchMethodError: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;
	at com.github.sejoslaw.catchEverythingInBook.CatchBlockHandler.handleSave(CatchBlockHandler.java:59)
	at com.github.sejoslaw.catchEverythingInBook.CatchBlockHandler.onRightClick(CatchBlockHandler.java:45)
	at net.minecraftforge.eventbus.ASMEventHandler_451_CatchBlockHandler_onRightClick_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:782)
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:313)
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847)
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36)
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626)
	at java.lang.Thread.run(Unknown Source)

[17Nov2019 11:27:47.250] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;
	at com.github.sejoslaw.catchEverythingInBook.CatchBlockHandler.handleSave(CatchBlockHandler.java:59) ~[?:1.14.4-1.0.0-forge]
	at com.github.sejoslaw.catchEverythingInBook.CatchBlockHandler.onRightClick(CatchBlockHandler.java:45) ~[?:1.14.4-1.0.0-forge]
	at net.minecraftforge.eventbus.ASMEventHandler_451_CatchBlockHandler_onRightClick_RightClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:782) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:313) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[17Nov2019 11:27:47.279] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: C:\Users\Monika\Desktop\Test Server 2.0\.\crash-reports\crash-2019-11-17_11.27.47-server.txt
[17Nov2019 11:27:47.280] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[17Nov2019 11:27:47.282] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[17Nov2019 11:27:47.388] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds

**Comment by dbock1989** [comment]
It works in single player no issue, same mods. You recreate it by Going on a server and trying to catch anything.

**Comment by Sejoslaw** [comment]
Fixed in 1.0.1
